# Numpy

NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing. It provides support for:

* Multidimensional Arrays: A core feature of NumPy is its ndarray object, which represents a multidimensional array of elements of the same type, enabling efficient storage and manipulation of data.
* Mathematical Functions: NumPy includes a comprehensive collection of mathematical functions for operations such as linear algebra, statistical analysis, Fourier transforms, and more.
* Vectorized Operations: It allows for element-wise operations on arrays, reducing the need for explicit loops and optimizing performance.
* Interoperability: It integrates well with other scientific libraries and is commonly used in combination with libraries like SciPy, Pandas, and Matplotlib.

In [2]:
import numpy as np 
# we are using np as the alias cause instead of numpy we can call np instead of numpy 

In [3]:
# Here we created the !D array using the numpy
arr1 = np.array([1 ,2  ,3 , 4, 5])
print("The 1D Dimensional of the array is " ,arr1)

# Here u can ask Questions that Its like a list how do u name as the array here we can able to see by using the type 
print("The type of the array is " ,type(arr1))

print("The shape of the array is :" , arr1.shape)

# The output for the shape of the array is (5 , ) That is because we are using the 1 Dimensional 
# There wont have any rows or colmns here 

The 1D Dimensional of the array is  [1 2 3 4 5]
The type of the array is  <class 'numpy.ndarray'>
The shape of the array is : (5,)


In [7]:
# creating the 2D array 
arr2 = np.array([10,7,8,9,7])
arr2 = arr2.reshape(1,5) # reshape function is used to convert the 1 D to 2 D 
# where it is said to be 1 rows and the 5 columns
print(arr2) ## The Output is [[10  7  8  9  7]] the 2 box bracket shows that its 2 D ARRAY
print("The shape of the arraay 2 is " , arr2.shape)
print("The type of the array is : " , type(arr2)) # <class 'numpy.ndarray'> 

[[10  7  8  9  7]]
The shape of the arraay 2 is  (1, 5)
The type of the array is :  <class 'numpy.ndarray'>


In [10]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print("The shape of the array is :" , arr3.shape) # (2, 5)
# (2, 5) represent the 2 rows and the 5 columns 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The shape of the array is : (2, 5)


In [14]:
arr = np.arange(0,10,2).reshape(5,1) 
arr

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
arr_nums = np.ones((3,5)) # Here we can use the one and zero as they are inbuilt 
arr_zeros = np.zeros((3,5))
print(arr_nums)
print(arr_zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# Identity matrix we have the diagonal to be 1 and the rest would be 0
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [35]:
# Attributes of the Numpy array 
arr = np.array([[1,2,3],[4,5,6]])
print("Array : " , arr) # Array :  [[1 2 3]
print("The Dimenetionality of the array is : " , arr.ndim)
print("The shape of the array is : " , arr.shape)
print("The size of the array is : " , arr.size)
print("The type of the array is : " , type(arr))

Array :  [[1 2 3]
 [4 5 6]]
The Dimenetionality of the array is :  2
The shape of the array is :  (2, 3)
The size of the array is :  6
The type of the array is :  <class 'numpy.ndarray'>


In [38]:
# Numpy vectorization variable 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# addition of the array 
print("The addition of the array is :" , arr1 + arr2)

# Subtraction of the array
print("The subtraction of the array is :" , arr1 - arr2)

# Multiplication of the array
print("The multiplication of the array is :" , arr1 * arr2)

# Division of the array
print("The division of the array is :" , arr1 / arr2)



The addition of the array is : [ 7  9 11 13 15]
The subtraction of the array is : [-5 -5 -5 -5 -5]
The multiplication of the array is : [ 6 14 24 36 50]
The division of the array is : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [41]:
# Universal Function 
arr = np.array([1,2,3,4,5,6])


# Square root of the array
print("The square root of the array is : " , np.sqrt(arr))

# Exponential of the array
print("The exponential of the array is : " , np.exp(arr))

# Logarithm of the array
print("The logarithm of the array is : " , np.log(arr))

# sin of the array 
print("The sin of the array is : " , np.sin(arr))

# cos of the array
print("The cos of the array is : " , np.cos(arr))

# tan of the array
print("The tan of the array is : " , np.tan(arr))

# Absolute value of the array
print("The absolute value of the array is : " , np.abs(arr))

The square root of the array is :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
The exponential of the array is :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
The logarithm of the array is :  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
The sin of the array is :  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
The cos of the array is :  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
The tan of the array is :  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
The absolute value of the array is :  [1 2 3 4 5 6]
